### ISSUE TITLE
Fails with newer version of node (I'm using 6.9.4)

### ISSUE THREAD

**Issue by purplejacket** [jonkemp/node-hello-world#1]
$ npm start

> beeportal@0.0.1 start /Users/kai/beeportal
> node server.js

/Users/kai/beeportal/server.js:3
var app = express.createServer();
                  ^

TypeError: express.createServer is not a function
    at Object.<anonymous> (/Users/kai/beeportal/server.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by jonkemp** [comment]
My apologies but this is very out of date. I wrote this example over three years ago. I would imagine it needs to be updated.
